spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-auth-app
  template:
    metadata:
      labels:
        app: my-auth-app
        version: v3.2.0
    spec:
      containers:
        - name: my-auth-app
          image: gcr.io/verdant-tempest-376308/myauthapp:mailservice-0.0.1-SNAPSHOT
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8081
          env:
            - name: VERSION
              value: v1.0.0
            - name: SMTP_EMAIL
              valueFrom:
                secretKeyRef:
                  name: smtp-credentials
                  key: smtp_username
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smtp-credentials
                  key: smtp_password
            - name: PROFILE
              value: cloud