apiVersion: v1
kind: Service
metadata:
  name: my-auth-front-end-svc
spec:
  selector:
    app: my-auth-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3080
  type: LoadBalancer