kind: Deployment
metadata:
  name: my-auth-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-auth-frontend
  template:
    metadata:
      labels:
        app: my-auth-frontend
        version: v1.1.8
    spec:
      containers:
        - name: my-auth-frontend
          image: gcr.io/verdant-tempest-376308/myauthapp-frontend:auth-frontend-0.0.1-SNAPSHOT
          imagePullPolicy: "Always"
          ports:
            - containerPort: 3080